### PR TITLE
upgrade to CSV 0.5

### PR DESCRIPTION
**Pull request by bjarthur**
fixes https://github.com/johnmyleswhite/RDatasets.jl/issues/69

### CODE REVIEW

**Comment by bjarthur** [comment]
tests now pass.  any comments?  @randyzwitch

**Comment by randyzwitch** [comment]
Does this PR also fix the issue being worked on in #68?

**Comment by bjarthur** [comment]
yes, it does.  gap::PD is one of a handful of datasets which require special treatment to get the types of columns correct. that PR completely ignores `Dataset_typedetect_rows` above.  this one modifies it to work with the new CSV API.

**Comment by SimonDanisch** [comment]
Would be great to merge this :)

**Pull request merged**
