### PR TITLE
Circumvent TranscodingStream position issue

### LINKED ISSUE #61: Can't open Gzipped dataset
```julia
julia> dataset("MASS", "Boston")
ERROR: MethodError: no method matching position(::TranscodingStream{CodecZlib.GzipDecompressor,IOStream})
Closest candidates are:
  position(::IOStream) at iostream.jl:188
  position(::Base.Libc.FILE) at libc.jl:101
  position(::Base.Filesystem.File) at filesystem.jl:225
  ...
Stacktrace:
 [1] consumeBOM!(::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}) at C:\Users\ohadl\.julia\packages\CSV\uLyo0\src\CSV.jl:209
 [2] #File#1(::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Nothing, ::Bool, ::Nothing, ::Bool, ::Array{String,1}, ::String, ::Char, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Type,Type}, ::Symbol, ::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:rows_for_type_detect,),Tuple{Int64}}}, ::Type, ::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}) at C:\Users\ohadl\.julia\packages\CSV\uLyo0\src\CSV.jl:142
 [3] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:delim, :quotechar, :missingstring, :rows_for_type_detect),Tuple{Char,Char,String,Int64}}, ::Type{CSV.File}, ::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}) at .\none:0
 [4] #read#101(::Bool, ::Dict{Int64,Function}, ::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:delim, :quotechar, :missingstring, :rows_for_type_detect),Tuple{Char,Char,String,Int64}}}, ::Function, ::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}, ::Type) at C:\Users\ohadl\.julia\packages\CSV\uLyo0\src\CSV.jl:304
 [5] (::getfield(CSV, Symbol("#kw##read")))(::NamedTuple{(:delim, :quotechar, :missingstring, :rows_for_type_detect),Tuple{Char,Char,String,Int64}}, ::typeof(CSV.read), ::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}, ::Type) at .\none:0 (repeats 2 times)
 [6] (::getfield(RDatasets, Symbol("##1#2")){String,String})(::TranscodingStream{CodecZlib.GzipDecompressor,IOStream}) at C:\Users\ohadl\.julia\packages\RDatasets\mvYPU\src\dataset.jl:27
 [7] open(::getfield(RDatasets, Symbol("##1#2")){String,String}, ::Type{TranscodingStream{CodecZlib.GzipDecompressor,S} where S<:IO}, ::String, ::String) at C:\Users\ohadl\.julia\packages\TranscodingStreams\SaPZ8\src\stream.jl:157
 [8] dataset(::String, ::String) at C:\Users\ohadl\.julia\packages\RDatasets\mvYPU\src\dataset.jl:26
 [9] top-level scope at none:0
```
Adding various packages didn't help.
Maybe an API changed? [This looks similar](https://stackoverflow.com/questions/52590792/how-do-i-read-a-gzipped-csv-file-in-julia).

### PR DESCRIPTION
**Pull request by laborg**
By completely  decompressing gzipped datasets into a string we bypass the current problem, caused by TranscodingStreams not having all IOStream functions defined (e.g `position` or `seek`).

Until this is implemented (see https://github.com/bicycle1885/TranscodingStreams.jl/issues/62) this PR fixes:
 - https://github.com/johnmyleswhite/RDatasets.jl/issues/61

and helps Gadfly as mentioned here:
 - https://github.com/bicycle1885/CodecZlib.jl/issues/32

Additionally I've fixed the Ecdat::Mofa dataset, so now all tests are passing again on Julia 1.0.1.

### CODE REVIEW

**Comment by bjarthur** [comment]
might this fail for some future dataset whose string can't all fit into memory?  i'm not sure, but the current code seems to lazily read it in.

**Comment by laborg** [comment]
Yes of course. The question is how likely this is going to be:
- The largest CSV dataset is 9mb (uncompressed)
- The last data set has been added two years ago

Telling the future is not possible, but my guess would be that not many huge CSV datasets will be added to RDatasets in the next couple of years.
From my point of view this negligible risk is way better than having a myriad of examples in published tutorials/books/packages/etc fail.

**Comment by randyzwitch** [comment]
I agree that worrying about out-of-memory errors in this package is unlikely. As it is, the package works well as a collection of well-known datasets, but I don't see it growing in size as it's not intended as a dumping ground for all future datasets.

I'll leave this open for comments for another few days, then merge if there are no other objections.

**Comment by alejandromerchan** [comment]
This should be merged, despite the mentioned risk. I, personally, have been a little stalled by this and would like a quick fix. I also realize that once the TranscodingStreams.jl - CSV.jl issue is solved, you could change this back to the old behavior.

**Comment by tlnagy** [comment]
Hey @randyzwitch, any chance we can get this merged and tagged? It's been breaking Gadfly's tests for weeks now.

**Pull request merged**
