### PR TITLE
change to only run 0.6 and nightly

### PR DESCRIPTION
**Pull request by StoneCypher**
for https://github.com/johnmyleswhite/RDatasets.jl/pull/48#issuecomment-356650289

### CODE REVIEW

**Comment by StoneCypher** [comment]
@randyzwitch

**Comment by StoneCypher** [comment]
@alyst

**Comment by randyzwitch** [comment]
Thanks

**Comment by StoneCypher** [comment]
it looks like nightly still fails

**Comment by randyzwitch** [comment]
That's fine, 0.6 is still the stable version

**Pull request merged**
